// For All
export const GET_ERROR = "GET_ERROR";

// Categories section

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";

export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const GET_SPECIAL_CATEGORY = "GET_SPECIAL_CATEGORY";

// Subcategory section

export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";

export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY";

export const GET_SUBCATEGORY_BY_CATEGORY = "GET_SUBCATEGORY_BY_CATEGORY";

// Brands Section

export const GET_ALL_BRANDS = "GET_ALL_BRANDS";

export const CREATE_BRAND = "CREATE_BRAND";

export const GET_SPECIAL_BRAND = "GET_SPECIAL_BRAND";

// Product Section

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const CREATE_PRODUCT = "CREATE_PRODUCT";

export const GET_SPECIAL_PRODUCT = "GET_SPECIAL_PRODUCT";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";