// For All
export const GET_ERROR = "GET_ERROR";

// Categories section

export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";

export const CREATE_CATEGORY = "CREATE_CATEGORY";

export const GET_SPECIAL_CATEGORY = "GET_SPECIAL_CATEGORY";

// Subcategory section

export const CREATE_SUBCATEGORY = "CREATE_SUBCATEGORY";

export const GET_ALL_SUBCATEGORY = "GET_ALL_SUBCATEGORY";

export const GET_SUBCATEGORY_BY_CATEGORY = "GET_SUBCATEGORY_BY_CATEGORY";

// Brands Section

export const GET_ALL_BRANDS = "GET_ALL_BRANDS";

export const CREATE_BRAND = "CREATE_BRAND";

export const GET_SPECIAL_BRAND = "GET_SPECIAL_BRAND";

// Product Section

export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";

export const CREATE_PRODUCT = "CREATE_PRODUCT";

export const GET_SPECIAL_PRODUCT = "GET_SPECIAL_PRODUCT";

export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";

export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";


// Authentication

export const LOGIN_USER = "LOGIN_USER";

export const REGISTER_USER = "REGISTER_USER";

export const LOGOUT_USER = "LOGOUT_USER";

export const FORGET_PASSWORD = "FORGET_PASSWORD";

export const VERIFY_RESET_CODE = "VERIFY_RESET_CODE"

export const RESET_PASSWORD = "RESET_PASSWORD"


// Reviewing

export const CREATE_REVIEW = "CREATE_REVIEW";

export const ALL_REVIEWS_PRODUCT = "ALL_REVIEWS_PRODUCT"

export const DELETE_SPECIFIC_REVIEW = "DELETE_SPECIFIC_REVIEW"

export const UPDATE_SPECIFIC_REVIEW = "UPDATE_SPECIFIC_REVIEW"


// WishList

export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST"

export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST"

export const GET_ALL_PRODUCTS_FROM_WISHLIST = "GET_ALL_PRODUCTS_FROM_WISHLIST"


// Coupons

export const CREATE_COUPON = "CREATE_COUPON"

export const GET_ALL_COUPONS = "GET_ALL_COUPONS"

export const DELETE_COUPON = "DELETE_COUPON"

export const UPDATE_SPECIFIC_COUPON = "UPDATE_SPECIFIC_COUPON"

export const GET_SPECIFIC_COUPON = "GET_SPECIFIC_COUPON"


// Address 

export const CREATE_ADDRESS = "CREATE_ADDRESS"

export const GET_ALL_ADDRESSES = "GET_ALL_ADDRESSES"

export const DELETE_ADDRESS = "DELETE_ADDRESS"

export const GET_SPECIFIC_ADDRESS = "GET_SPECIFIC_ADDRESS"

export const UPDATE_SPECIFIC_ADDRESS = "UPDATE_SPECIFIC_ADDRESS"


// User Profile

export const UPDATE_USER_DATA = "UPDATE_USER_DATA"

export const UPDATE_USER_PASSWORD = "UPDATE_USER_PASSWORD"


// Cart

export const ADD_TO_CART = "ADD_TO_CART"

export const GET_CART_ITEMS = "GET_CART_ITEMS"

export const REMOVE_FROM_CART = "REMOVE_FROM_CART"

export const UPDATE_CART_ITEM_COUNT = "UPDATE_CART_ITEM_COUNT"

export const CLEAR_CART = "CLEAR_CART"

export const APPLY_COUPON = "APPLY_COUPON"